resources:
  packages:
   - package: somePackage
     type: Nuget
     connection: gh-rg
     name: nugetTest/OctocatApp
     version: 2.1.10
     trigger: true
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: Default
       steps:
        - getPackage: somePackage
