trigger: none
resources:
  packages:
   - package: somePackage
     type: Nuget
     connection: gh-rg
     name: nugetTest/OctocatApp
     trigger: true
     
stages:
 - stage: ConsumeArtifact
   jobs:
     - job: job1
       pool: 
        name: rogoyal
       steps:
        - getPackage: somePackage
